#!/bin/sh

set -e

source "${JBOSS_CONTAINER_UTIL_LOGGING_MODULE}/logging.sh"
source "${JBOSS_CONTAINER_S2I_CORE_MODULE}/s2i-core"
source "${JBOSS_CONTAINER_AMQ_S2I_MODULE}/s2i-core-hooks"

# Initialize the core s2i module
s2i_core_init

# Copy any artifacts out of the source directory (configuration, data, deployment)
s2i_core_copy_artifacts "${S2I_SOURCE_DIR}"

# Copy any artifacts contributed through image sources
s2i_core_process_image_mounts

# Cleanup
s2i_core_cleanup
