#!/bin/sh
set -e

SOURCES_DIR="/tmp/artifacts"

# for backward compatibility.  jolokia is now located in /opt/jolokia.
# Add Jolokia (http://www.jolokia.org/) to expose all MBeans
ln -s /opt/jolokia/jolokia.jar $JWS_HOME/lib/jolokia.jar
