schema_version: 1
name: jboss.container.eap.prometheus.agent
version: '1.0'
description: Provides support for configuring the Prometheus JMX Exporter Java agent within EAP

modules:
  install:
  - name: jboss.container.prometheus.bash

execute:
- script: configure.sh
  user: '185'
