#!/bin/sh

if [ "${SCRIPT_DEBUG}" = "true" ] ; then
    set -x
    echo "Script debugging is enabled, allowing bash commands and their arguments to be printed as they are executed"
fi

SRCCONF=/tmp/src/configuration

if [ -d ${SRCCONF} ]; then
  echo "Copying config files from project..."
  cp -v ${SRCCONF}/* $AMQ_HOME/conf/
fi

exit 0
