schema_version: 1

name: jboss.container.prometheus.bash
version: '1.0'
description: ^
  Provides support for configuring Prometheus.  Basic usage is
  JAVA_OPTS="$JAVA_OPTS $(source $JBOSS_CONTAINER_PROMETHEUS_MODULE/prometheus-opts; get_prometheus_opts)"

envs:
- name: JBOSS_CONTAINER_PROMETHEUS_MODULE
  value: /opt/jboss/container/prometheus
- name: AB_PROMETHEUS_JMX_EXPORTER_PORT
  value: 9799
- name: AB_PROMETHEUS_JMX_EXPORTER_CONFIG
  value: /opt/jboss/container/prometheus/etc/jmx-exporter-config.yaml

execute:
- script: configure.sh

artifacts:
- name: jmx_prometheus_javaagent
  target: jmx_prometheus_javaagent-0.3.2.redhat-00005.jar
  md5: 2cd8f7055b99fff305a74b0581e8ecd3

modules:
  install:
  - name: jboss.container.prometheus.api
